//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace XRTK.Lumin.Native.Bindings
{
    internal static class MlCloud
    {
        /// <summary>
        ///  InAppPurchases
        /// General result codes for Cloud API calls
        /// </summary>
        /// <remarks>
        /// \
        /// {
        /// </remarks>
        public const int MLResultAPIPrefix_Cloud = unchecked((int)0xc4e3 << 16);

        /// <summary>
        /// Return values for Cloud API calls
        /// </summary>
        public enum MLCloudResult : int
        {
            /// <summary>
            /// The requested resource was not found on the server
            /// </summary>
            MLCloudResult_NotFound = unchecked((int)MLResultAPIPrefix_Cloud),

            /// <summary>
            /// The server failed to process the request
            /// </summary>
            MLCloudResult_ServerError,

            /// <summary>
            /// The request may not have made it to the server The service did not receive a response from the server
            /// </summary>
            MLCloudResult_NetworkError,

            /// <summary>
            /// Some unexpected system error prevented the request from getting to
            /// the cloud This is most likely a bug in the API implementation
            /// </summary>
            MLCloudResult_SystemError,

            /// <summary>
            /// The handle that was passed in is not a valid handle for the API call it was used in
            /// </summary>
            MLCloudResult_InvalidHandle,

            /// <summary>
            /// The handle was used too soon
            /// </summary>
            MLCloudResult_BadHandleState,

            /// <summary>
            /// Ensure enum is represented as 32 bits
            /// </summary>
            MLCloudResult_Ensure32Bits = unchecked((int)0x7FFFFFFF),
        }

        /// <summary>
        /// This represents the polling status of an asynchronous cloud call
        /// </summary>
        public enum MLCloudStatus : int
        {
            /// <summary>
            /// The current request is still in-progress
            /// </summary>
            MLCloudStatus_NotDone = unchecked((int)0),

            /// <summary>
            /// The current request is complete It may have succeeded or failed
            /// </summary>
            MLCloudStatus_Done,

            /// <summary>
            /// Ensure enum is represented as 32 bits
            /// </summary>
            MLCloudStatus_Ensure32Bits = unchecked((int)0x7FFFFFFF),
        }
    }
}
