//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace XRTK.Lumin.Native.Bindings
{
    using System.Runtime.InteropServices;

    internal static class MlMediaTypes
    {
        /// <summary>
        /// PSSH entry
        /// </summary>
        [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Ansi)]
        public struct MLPSSHEntry
        {
            /// <summary>
            /// 16 bytes UUID specifying crypto scheme
            /// </summary>
            public MlTypes.MLUUID uuid;

            /// <summary>
            /// Size of the data payload
            /// </summary>
            public Interop.size_t size;

            /// <summary>
            /// Data specific to that scheme
            /// </summary>
            public IntPtr data;
        }
    }
}
