//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace XRTK.Lumin.Native.Bindings
{
    using System.Runtime.InteropServices;

    internal static class MlPlatform
    {
        /// <summary>
        /// Query the OS for which Platform API Level is supported
        /// </summary>
        /// <param name="out_api_level">Pointer to an integer that will store the API level</param>
        /// <returns>
        /// MLResult_Ok Operation completed successfully
        /// MLResult_InvalidParam out_platform_level was not valid (null)
        /// MLResult_UnspecifiedError Operation failed
        /// </returns>
        /// <remarks>
        /// @priv None
        /// </remarks>
        [DllImport("ml_platform", CallingConvention = CallingConvention.Cdecl)]
        public static extern MlApi.MLResult MLPlatformGetAPILevel(ref uint out_api_level);
    }
}
